CREATE TABLE applicant
(
    applicant_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    status        VARCHAR(255),
    approved_by   VARCHAR(255),
    approved_date TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255)                            NOT NULL,
    updated_by    VARCHAR(255),
    created_date  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_date  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_applicant PRIMARY KEY (applicant_id)
);
