CREATE TABLE loan
(
    loan_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_facility_id BIGINT                                  NOT NULL,
    type               VARCHAR(255)                            NOT NULL,
    principal          DECIMAL(38, 2)                          NOT NULL,
    interest_date      DECIMAL(8, 5)                           NOT NULL,
    status             VARCHAR(255)                            NOT NULL,
    start_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    approved_by        VARCHAR(255),
    approved_date      TIMESTAMP WITHOUT TIME ZONE,
    created_by         VARCHAR(255)                            NOT NULL,
    updated_by         VARCHAR(255),
    created_date       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_date       TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_loan PRIMARY KEY (loan_id)
);

ALTER TABLE loan
    ADD CONSTRAINT FK_LOAN_ON_CREDIT_FACILITY FOREIGN KEY (credit_facility_id) REFERENCES credit_facility (credit_facility_id);