CREATE TABLE credit_limit
(
    credit_limit_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    credit_limit      DECIMAL(38, 2)                          NOT NULL,
    credit_limit_date date                                    NOT NULL,
    created_by        VARCHAR(255)                            NOT NULL,
    updated_by        VARCHAR(255),
    created_date      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_date      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_credit_limit PRIMARY KEY (credit_limit_id)
);
